# Site settings
title: Skosh Interactive
email: info@skosh.io
description: > # this means to ignore newlines until "baseurl:"
  Learn about Skosh Interactive.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://teamskosh.github.io/" # the base hostname & protocol for your site
twitter_username: teamskosh
github_username:  teamskosh

# Build settings
markdown: kramdown

exclude: [
  _scss,
  .git,
  .gitignore,
  .DS_Store,
  .sass-cache,
  bower_components,
  Gruntfile.js,
  node_modules,
  package.json,
  README.md
]
